# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeStatus_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_changeStatus_window(object):
    def setupUi(self, changeStatus_window):
        changeStatus_window.setObjectName("changeStatus_window")
        changeStatus_window.resize(500, 500)
        changeStatus_window.setMinimumSize(QtCore.QSize(500, 500))
        changeStatus_window.setMaximumSize(QtCore.QSize(500, 500))
        changeStatus_window.setStyleSheet("background-color: rgb(0, 127, 255);\n"
"color: white;\n"
"font-family: \"Calibri Light\";\n"
"font-size: 20px;")
        self.centralwidget = QtWidgets.QWidget(changeStatus_window)
        self.centralwidget.setObjectName("centralwidget")
        self.phase_status = QtWidgets.QLabel(self.centralwidget)
        self.phase_status.setGeometry(QtCore.QRect(20, 250, 451, 31))
        self.phase_status.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.phase_status.setObjectName("phase_status")
        self.greenlight_count = QtWidgets.QLabel(self.centralwidget)
        self.greenlight_count.setGeometry(QtCore.QRect(20, 300, 451, 31))
        self.greenlight_count.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.greenlight_count.setObjectName("greenlight_count")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 471, 201))
        self.label.setStyleSheet("border: 2px solid white;\n"
"border-radius: 15px;\n"
"font-size: 20px;\n"
"background-color: green;\n"
"color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.changeStatus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.changeStatus_btn.setGeometry(QtCore.QRect(150, 360, 191, 51))
        self.changeStatus_btn.setStyleSheet("background-color: green;\n"
"color: white;\n"
"font-size: 20px;\n"
"border: 2px solid white;")
        self.changeStatus_btn.setObjectName("changeStatus_btn")
        self.changeStatus_cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.changeStatus_cancel_btn.setGeometry(QtCore.QRect(150, 430, 191, 51))
        self.changeStatus_cancel_btn.setStyleSheet("background-color: red;\n"
"color: white;\n"
"font-size: 20px;\n"
"border: 2px solid white;")
        self.changeStatus_cancel_btn.setObjectName("changeStatus_cancel_btn")
        changeStatus_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(changeStatus_window)
        QtCore.QMetaObject.connectSlotsByName(changeStatus_window)

    def retranslateUi(self, changeStatus_window):
        _translate = QtCore.QCoreApplication.translate
        changeStatus_window.setWindowTitle(_translate("changeStatus_window", "Close Phase"))
        self.phase_status.setText(_translate("changeStatus_window", "<Current Status:>"))
        self.greenlight_count.setText(_translate("changeStatus_window", "<Phase closure greenlights:>"))
        self.label.setText(_translate("changeStatus_window", "This window allows admins to close this phase. Do note that this step is IRREVERSIBLE. Please ensure that all relevant figure heads agree on the closure of this phase despite this system needing all their manual approval to close the phase."))
        self.changeStatus_btn.setText(_translate("changeStatus_window", "Close Phase"))
        self.changeStatus_cancel_btn.setText(_translate("changeStatus_window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changeStatus_window = QtWidgets.QMainWindow()
    ui = Ui_changeStatus_window()
    ui.setupUi(changeStatus_window)
    changeStatus_window.show()
    sys.exit(app.exec_())
