# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'issue_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_issueCard_window(object):
    def setupUi(self, issueCard_window):
        issueCard_window.setObjectName("issueCard_window")
        issueCard_window.resize(1200, 700)
        issueCard_window.setMinimumSize(QtCore.QSize(1200, 700))
        issueCard_window.setMaximumSize(QtCore.QSize(1200, 700))
        issueCard_window.setStyleSheet("background-color:rgb(0, 127, 255);\n"
"font-famiily: \"Calibri Light\";\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(issueCard_window)
        self.centralwidget.setObjectName("centralwidget")
        self.issue_issueTitkle = QtWidgets.QLabel(self.centralwidget)
        self.issue_issueTitkle.setGeometry(QtCore.QRect(10, 10, 181, 21))
        self.issue_issueTitkle.setStyleSheet("font-size: 20px;\n"
"border: none")
        self.issue_issueTitkle.setAlignment(QtCore.Qt.AlignCenter)
        self.issue_issueTitkle.setObjectName("issue_issueTitkle")
        self.issue_issueCode = QtWidgets.QLabel(self.centralwidget)
        self.issue_issueCode.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.issue_issueCode.setStyleSheet("font-size: 20px;\n"
"border: none")
        self.issue_issueCode.setAlignment(QtCore.Qt.AlignCenter)
        self.issue_issueCode.setObjectName("issue_issueCode")
        self.issue_raisedDate = QtWidgets.QLabel(self.centralwidget)
        self.issue_raisedDate.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.issue_raisedDate.setStyleSheet("font-size: 20px;\n"
"border: none")
        self.issue_raisedDate.setAlignment(QtCore.Qt.AlignCenter)
        self.issue_raisedDate.setObjectName("issue_raisedDate")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 110, 761, 571))
        self.tableView.setStyleSheet("background-color: \"light gray\";\n"
"color: black;\n"
"border: 2px solid black;")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 791, 811))
        self.groupBox.setStyleSheet("border: 2px solid white;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.setStatus_btn_3 = QtWidgets.QPushButton(self.groupBox)
        self.setStatus_btn_3.setGeometry(QtCore.QRect(630, 50, 141, 41))
        self.setStatus_btn_3.setStyleSheet("background-color: red;\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold")
        self.setStatus_btn_3.setObjectName("setStatus_btn_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 10, 191, 41))
        self.label.setStyleSheet("font-size: 20px;\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.requestExtention_date_display = QtWidgets.QLineEdit(self.centralwidget)
        self.requestExtention_date_display.setGeometry(QtCore.QRect(800, 50, 391, 41))
        self.requestExtention_date_display.setStyleSheet("background-color: \"light gray\";\n"
"border: 2px solid black;\n"
"font-size: 20px;")
        self.requestExtention_date_display.setObjectName("requestExtention_date_display")
        self.setStatus_btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.setStatus_btn_5.setGeometry(QtCore.QRect(1040, 100, 151, 41))
        self.setStatus_btn_5.setStyleSheet("background-color: green;\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;")
        self.setStatus_btn_5.setObjectName("setStatus_btn_5")
        self.requestExtention_date_selection_btn = QtWidgets.QPushButton(self.centralwidget)
        self.requestExtention_date_selection_btn.setGeometry(QtCore.QRect(800, 100, 151, 41))
        self.requestExtention_date_selection_btn.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: black;\n"
"border: 2px solid black;\n"
"border-radius: none;\n"
"font-size: 15px;")
        self.requestExtention_date_selection_btn.setObjectName("requestExtention_date_selection_btn")
        self.issue_postUpdate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.issue_postUpdate_btn.setGeometry(QtCore.QRect(920, 620, 141, 41))
        self.issue_postUpdate_btn.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid black;\n"
"border-radius: none;\n"
"font-size: 15px;")
        self.issue_postUpdate_btn.setObjectName("issue_postUpdate_btn")
        self.setStatus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.setStatus_btn.setGeometry(QtCore.QRect(1040, 160, 151, 41))
        self.setStatus_btn.setStyleSheet("background-color: green;\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold")
        self.setStatus_btn.setObjectName("setStatus_btn")
        self.setStatus_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.setStatus_btn_2.setGeometry(QtCore.QRect(800, 160, 151, 41))
        self.setStatus_btn_2.setStyleSheet("background-color: red;\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold")
        self.setStatus_btn_2.setObjectName("setStatus_btn_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(900, 260, 191, 41))
        self.label_2.setStyleSheet("font-size: 20px;\n"
"border: none;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.issue_postUpdate_input = QtWidgets.QTextEdit(self.centralwidget)
        self.issue_postUpdate_input.setGeometry(QtCore.QRect(810, 300, 371, 291))
        self.issue_postUpdate_input.setStyleSheet("background-color: white;\n"
"border: 2px solid white;\n"
"color: black;\n"
"font-size: 20px;")
        self.issue_postUpdate_input.setObjectName("issue_postUpdate_input")
        self.groupBox.raise_()
        self.issue_issueTitkle.raise_()
        self.issue_issueCode.raise_()
        self.issue_raisedDate.raise_()
        self.tableView.raise_()
        self.label.raise_()
        self.requestExtention_date_display.raise_()
        self.setStatus_btn_5.raise_()
        self.requestExtention_date_selection_btn.raise_()
        self.issue_postUpdate_btn.raise_()
        self.setStatus_btn.raise_()
        self.setStatus_btn_2.raise_()
        self.label_2.raise_()
        self.issue_postUpdate_input.raise_()
        issueCard_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(issueCard_window)
        QtCore.QMetaObject.connectSlotsByName(issueCard_window)

    def retranslateUi(self, issueCard_window):
        _translate = QtCore.QCoreApplication.translate
        issueCard_window.setWindowTitle(_translate("issueCard_window", "Issue"))
        self.issue_issueTitkle.setText(_translate("issueCard_window", "<Issue>"))
        self.issue_issueCode.setText(_translate("issueCard_window", "<Issue Code>"))
        self.issue_raisedDate.setText(_translate("issueCard_window", "<Raised Date>"))
        self.setStatus_btn_3.setText(_translate("issueCard_window", "CLOSE ISSUE"))
        self.label.setText(_translate("issueCard_window", "Request Extention"))
        self.setStatus_btn_5.setText(_translate("issueCard_window", "Request"))
        self.requestExtention_date_selection_btn.setText(_translate("issueCard_window", "Choose Date"))
        self.issue_postUpdate_btn.setText(_translate("issueCard_window", "Post Update"))
        self.setStatus_btn.setText(_translate("issueCard_window", "APPROVE"))
        self.setStatus_btn_2.setText(_translate("issueCard_window", "DENY"))
        self.label_2.setText(_translate("issueCard_window", "Post Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    issueCard_window = QtWidgets.QMainWindow()
    ui = Ui_issueCard_window()
    ui.setupUi(issueCard_window)
    issueCard_window.show()
    sys.exit(app.exec_())
