# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'issueExtention_calendar_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 632)
        MainWindow.setStyleSheet("background-color: rgb(0, 127, 255);\n"
"color: white;\n"
"font-family: \"Calibri-light\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.requestExtention_calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.requestExtention_calendar.setGeometry(QtCore.QRect(0, 0, 841, 501))
        self.requestExtention_calendar.setStyleSheet("background-color: white;\n"
"border: 2px solid black;\n"
"color: black;")
        self.requestExtention_calendar.setGridVisible(True)
        self.requestExtention_calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.requestExtention_calendar.setNavigationBarVisible(True)
        self.requestExtention_calendar.setDateEditEnabled(False)
        self.requestExtention_calendar.setObjectName("requestExtention_calendar")
        self.chosenDate_display = QtWidgets.QLineEdit(self.centralwidget)
        self.chosenDate_display.setGeometry(QtCore.QRect(230, 520, 351, 31))
        self.chosenDate_display.setStyleSheet("background-color: \"Light gray\";\n"
"color: white;\n"
"border: 2px solid white;\n"
"font-size: 20px;")
        self.chosenDate_display.setAlignment(QtCore.Qt.AlignCenter)
        self.chosenDate_display.setObjectName("chosenDate_display")
        self.requestExtention_date_selection_btn = QtWidgets.QPushButton(self.centralwidget)
        self.requestExtention_date_selection_btn.setGeometry(QtCore.QRect(340, 560, 151, 41))
        self.requestExtention_date_selection_btn.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: black;\n"
"border: 2px solid black;\n"
"border-radius: none;\n"
"font-size: 15px;")
        self.requestExtention_date_selection_btn.setObjectName("requestExtention_date_selection_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extention Calendar"))
        self.requestExtention_date_selection_btn.setText(_translate("MainWindow", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
