# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(500, 500)
        login_window.setMinimumSize(QtCore.QSize(500, 500))
        login_window.setMaximumSize(QtCore.QSize(500, 500))
        login_window.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 52, 151, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font-family: \"Calibri Light\";\n"
"color: black;")
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 160, 221, 41))
        self.label.setStyleSheet("font-size: 30px;\n"
"border: none;\n"
"background-color: none;\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 230, 221, 51))
        self.pushButton.setStyleSheet("background-color: white;\n"
"color: black;\n"
"font-size: 20px;\n"
"border: 2px solid black;")
        self.pushButton.setObjectName("pushButton")
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Login"))
        self.label.setText(_translate("login_window", "Hello there"))
        self.pushButton.setText(_translate("login_window", "Login with Microsoft"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
