# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(1060, 617)
        login_window.setMinimumSize(QtCore.QSize(1060, 617))
        login_window.setMaximumSize(QtCore.QSize(1060, 617))
        font = QtGui.QFont()
        font.setKerning(False)
        login_window.setFont(font)
        login_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        login_window.setWindowOpacity(0.0)
        login_window.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 52, 151, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.loginWelcome_label = QtWidgets.QLabel(self.centralwidget)
        self.loginWelcome_label.setGeometry(QtCore.QRect(270, 140, 481, 101))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.loginWelcome_label.setFont(font)
        self.loginWelcome_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.loginWelcome_label.setAutoFillBackground(False)
        self.loginWelcome_label.setStyleSheet("background-color: none;\n"
"font-weight: bold;")
        self.loginWelcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loginWelcome_label.setObjectName("loginWelcome_label")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(350, 280, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font-size: 20px;\n"
"border: 2px solid white;\n"
"color: white;")
        self.login_btn.setObjectName("login_btn")
        login_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login_window)
        self.statusbar.setObjectName("statusbar")
        login_window.setStatusBar(self.statusbar)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Login"))
        self.loginWelcome_label.setText(_translate("login_window", "Hello there, welcome!"))
        self.login_btn.setText(_translate("login_window", "Login with Microsoft"))
