# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projects_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_projects_page(object):
    def setupUi(self, projects_page):
        projects_page.setObjectName("projects_page")
        projects_page.resize(1000, 800)
        projects_page.setMinimumSize(QtCore.QSize(1000, 800))
        projects_page.setMaximumSize(QtCore.QSize(1000, 800))
        projects_page.setStyleSheet("background-color: rgb(0, 127, 255)")
        self.centralwidget = QtWidgets.QWidget(projects_page)
        self.centralwidget.setObjectName("centralwidget")
        self.issuesPage_btn = QtWidgets.QTabWidget(self.centralwidget)
        self.issuesPage_btn.setGeometry(QtCore.QRect(0, 0, 1011, 801))
        self.issuesPage_btn.setObjectName("issuesPage_btn")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(380, 690, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: white;\n"
"color: black;\n"
"font-size: 20px;\n"
"border: 2px solid black;")
        self.pushButton.setObjectName("pushButton")
        self.projPage_proj_list = QtWidgets.QTableView(self.tab)
        self.projPage_proj_list.setGeometry(QtCore.QRect(0, 0, 1001, 681))
        self.projPage_proj_list.setObjectName("projPage_proj_list")
        self.issuesPage_btn.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.myIssues_table_list = QtWidgets.QTableView(self.tab_2)
        self.myIssues_table_list.setGeometry(QtCore.QRect(0, 50, 1001, 731))
        self.myIssues_table_list.setStyleSheet("background-color: \"light gray\";\n"
"color: white;\n"
"font-size: 20px;")
        self.myIssues_table_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.myIssues_table_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.myIssues_table_list.setObjectName("myIssues_table_list")
        self.myIssues_tab_issues_count = QtWidgets.QLabel(self.tab_2)
        self.myIssues_tab_issues_count.setGeometry(QtCore.QRect(10, 10, 471, 31))
        self.myIssues_tab_issues_count.setStyleSheet("font-size: 20px;\n"
"color: white;\n"
"background-color: none;\n"
"border: none;")
        self.myIssues_tab_issues_count.setObjectName("myIssues_tab_issues_count")
        self.issuesPage_btn.addTab(self.tab_2, "")
        projects_page.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(projects_page)
        self.statusbar.setObjectName("statusbar")
        projects_page.setStatusBar(self.statusbar)

        self.retranslateUi(projects_page)
        self.issuesPage_btn.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(projects_page)

    def retranslateUi(self, projects_page):
        _translate = QtCore.QCoreApplication.translate
        projects_page.setWindowTitle(_translate("projects_page", "<Hello user_id>"))
        self.pushButton.setText(_translate("projects_page", "Create a new project"))
        self.issuesPage_btn.setTabText(self.issuesPage_btn.indexOf(self.tab), _translate("projects_page", "My Projects"))
        self.myIssues_tab_issues_count.setText(_translate("projects_page", "<Total Issues: >"))
        self.issuesPage_btn.setTabText(self.issuesPage_btn.indexOf(self.tab_2), _translate("projects_page", "My Issues"))
