# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raiseIssue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_raiseIssue_window(object):
    def setupUi(self, raiseIssue_window):
        raiseIssue_window.setObjectName("raiseIssue_window")
        raiseIssue_window.resize(1200, 700)
        raiseIssue_window.setMinimumSize(QtCore.QSize(1200, 700))
        raiseIssue_window.setMaximumSize(QtCore.QSize(1200, 700))
        raiseIssue_window.setStyleSheet("background-color: rgb(0, 127, 255);\n"
"font-family: \"Calibri Light\";\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(raiseIssue_window)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 861, 711))
        self.groupBox.setStyleSheet("border: 2px solid white;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.label.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.raiseIssue_title_input = QtWidgets.QLineEdit(self.groupBox)
        self.raiseIssue_title_input.setGeometry(QtCore.QRect(130, 20, 691, 31))
        self.raiseIssue_title_input.setStyleSheet("border: 2px solid black;\n"
"background-color: white;\n"
"color: black;\n"
"font-size: 20px;")
        self.raiseIssue_title_input.setObjectName("raiseIssue_title_input")
        self.raiseIssue_issue_code = QtWidgets.QLabel(self.groupBox)
        self.raiseIssue_issue_code.setGeometry(QtCore.QRect(40, 90, 341, 31))
        self.raiseIssue_issue_code.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.raiseIssue_issue_code.setTextFormat(QtCore.Qt.AutoText)
        self.raiseIssue_issue_code.setAlignment(QtCore.Qt.AlignCenter)
        self.raiseIssue_issue_code.setObjectName("raiseIssue_issue_code")
        self.raiseIssue_issue_date = QtWidgets.QLabel(self.groupBox)
        self.raiseIssue_issue_date.setGeometry(QtCore.QRect(470, 90, 341, 31))
        self.raiseIssue_issue_date.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.raiseIssue_issue_date.setTextFormat(QtCore.Qt.AutoText)
        self.raiseIssue_issue_date.setAlignment(QtCore.Qt.AlignCenter)
        self.raiseIssue_issue_date.setObjectName("raiseIssue_issue_date")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 130, 821, 481))
        self.textEdit.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid black;")
        self.textEdit.setObjectName("textEdit")
        self.raiseIssue_ok_btn = QtWidgets.QPushButton(self.groupBox)
        self.raiseIssue_ok_btn.setGeometry(QtCore.QRect(520, 630, 131, 51))
        self.raiseIssue_ok_btn.setStyleSheet("background-color: green;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;")
        self.raiseIssue_ok_btn.setObjectName("raiseIssue_ok_btn")
        self.raiseIssue_cancel_btn = QtWidgets.QPushButton(self.groupBox)
        self.raiseIssue_cancel_btn.setGeometry(QtCore.QRect(240, 630, 131, 51))
        self.raiseIssue_cancel_btn.setStyleSheet("background-color: red;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold;\n"
"color: white;")
        self.raiseIssue_cancel_btn.setObjectName("raiseIssue_cancel_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 10, 141, 31))
        self.label_2.setStyleSheet("border: none;\n"
"font-size: 20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.raiseIssue_add_people_name_finder_input = QtWidgets.QLineEdit(self.centralwidget)
        self.raiseIssue_add_people_name_finder_input.setGeometry(QtCore.QRect(880, 40, 291, 31))
        self.raiseIssue_add_people_name_finder_input.setStyleSheet("border: 2px solid black;\n"
"background-color: white;\n"
"color: black;\n"
"font-size: 20px;")
        self.raiseIssue_add_people_name_finder_input.setObjectName("raiseIssue_add_people_name_finder_input")
        self.raiseIssue_people_display_table = QtWidgets.QTableView(self.centralwidget)
        self.raiseIssue_people_display_table.setGeometry(QtCore.QRect(880, 80, 291, 251))
        self.raiseIssue_people_display_table.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid black;")
        self.raiseIssue_people_display_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.raiseIssue_people_display_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.raiseIssue_people_display_table.setObjectName("raiseIssue_people_display_table")
        self.raiseIssue_added_people_table = QtWidgets.QTableView(self.centralwidget)
        self.raiseIssue_added_people_table.setGeometry(QtCore.QRect(880, 340, 291, 321))
        self.raiseIssue_added_people_table.setStyleSheet("background-color: \"Light gray\";\n"
"color: black;\n"
"border: 2px solid black;")
        self.raiseIssue_added_people_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.raiseIssue_added_people_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.raiseIssue_added_people_table.setObjectName("raiseIssue_added_people_table")
        raiseIssue_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(raiseIssue_window)
        QtCore.QMetaObject.connectSlotsByName(raiseIssue_window)

    def retranslateUi(self, raiseIssue_window):
        _translate = QtCore.QCoreApplication.translate
        raiseIssue_window.setWindowTitle(_translate("raiseIssue_window", "Raise Issue"))
        self.label.setText(_translate("raiseIssue_window", "Issue Title"))
        self.raiseIssue_issue_code.setText(_translate("raiseIssue_window", "<Issue Code:>"))
        self.raiseIssue_issue_date.setText(_translate("raiseIssue_window", "<Issue Date:>"))
        self.raiseIssue_ok_btn.setText(_translate("raiseIssue_window", "Ok"))
        self.raiseIssue_cancel_btn.setText(_translate("raiseIssue_window", "Cancel"))
        self.label_2.setText(_translate("raiseIssue_window", "Add People"))
