# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docsCategory_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_docsCategory_window(object):
    def setupUi(self, docsCategory_window):
        docsCategory_window.setObjectName("docsCategory_window")
        docsCategory_window.resize(1500, 1000)
        docsCategory_window.setMinimumSize(QtCore.QSize(1500, 1000))
        docsCategory_window.setMaximumSize(QtCore.QSize(1500, 1000))
        docsCategory_window.setStyleSheet("background-color: rgb(0, 127, 255);\n"
"color: white;\n"
"font-family:  \"Calibri Light\";")
        self.centralwidget = QtWidgets.QWidget(docsCategory_window)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -10, 1021, 1011))
        self.groupBox.setStyleSheet("border: 2px solid white;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.label.setStyleSheet("background-color: none;\n"
"border: none;\n"
"font-size: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(120, 30, 301, 31))
        self.comboBox.setStyleSheet("background-color: white;\n"
"color: black;\n"
"font-size: 20px;\n"
"border: 2px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setGeometry(QtCore.QRect(10, 80, 1001, 921))
        self.tableView.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid white;\n"
"font-size: 15px;")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableView.setObjectName("tableView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1220, 20, 111, 31))
        self.label_2.setStyleSheet("background-color: none;\n"
"border: none;\n"
"font-size: 20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setGeometry(QtCore.QRect(1030, 70, 461, 751))
        self.tableView_2.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid white;\n"
"font-size: 15px;")
        self.tableView_2.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableView_2.setObjectName("tableView_2")
        self.setStatus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.setStatus_btn.setGeometry(QtCore.QRect(1200, 870, 141, 41))
        self.setStatus_btn.setStyleSheet("background-color: green;\n"
"color: white;\n"
"border: 2px solid white;\n"
"border-radius: none;\n"
"font-size: 15px;\n"
"font-weight: bold")
        self.setStatus_btn.setObjectName("setStatus_btn")
        docsCategory_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(docsCategory_window)
        QtCore.QMetaObject.connectSlotsByName(docsCategory_window)

    def retranslateUi(self, docsCategory_window):
        _translate = QtCore.QCoreApplication.translate
        docsCategory_window.setWindowTitle(_translate("docsCategory_window", "<Docs Category>"))
        self.label.setText(_translate("docsCategory_window", "Document:"))
        self.label_2.setText(_translate("docsCategory_window", "Add Entry"))
        self.setStatus_btn.setText(_translate("docsCategory_window", "Add Entry"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    docsCategory_window = QtWidgets.QMainWindow()
    ui = Ui_docsCategory_window()
    ui.setupUi(docsCategory_window)
    docsCategory_window.show()
    sys.exit(app.exec_())
